# Generated by Django 3.2.9 on 2021-11-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tborders.orders')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tborders.user')),
            ],
        ),
    ]
